apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocdrocks
  name: gitlab_app
spec:
  project: argocdrocks-project
  source:
    repoURL: https://github.com/jcammas/jcammas-argocd.git # => changer le répo git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
