apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitlab_project
  labels:
    app: argocdrocks
spec:
  # Project description
  description: Our ArgoCD Project to deploy our app locally
  # Allow manifests to deploy only from Sokube git repositories
  sourceRepos:
    - "http://192.168.42.100:1515/root/*"
  # Only permit to deploy applications in the same cluster
  destinations:
    - namespace: gitlab
      server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
