USER_NAME = "Sithis"
USER_PASSWORD = "IOT"


Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "debian 11 bullseye64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = "mabouce_debian_11_bullseye64"
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2
  end



  # Update repositories
  config.vm.provision :shell, inline: "sudo apt-get update -y"

  # Upgrade installed packages
  config.vm.provision :shell, inline: "sudo apt-get upgrade -y"

  # # Add `USER_NAME` user
  # config.vm.provision :shell, inline: "sudo useradd -m -p "+ "$(echo '" + USER_PASSWORD + "' | openssl passwd -1 -stdin)" + " " + USER_NAME

  # # Add `USER_NAME` to Administrator
  # config.vm.provision :shell, inline: "sudo usermod -aG sudo " + USER_NAME

  # Vim
  config.vm.provision :shell, inline: "sudo apt-get install vim -y"
  # Git
  config.vm.provision :shell, inline: "sudo apt-get install git -y"

  # Install virtualbox
  config.vm.provision :shell, inline: "sudo apt install gnupg"
  config.vm.provision :shell, inline: "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -"
  config.vm.provision :shell, inline: "wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -"
  config.vm.provision :shell, inline: "echo 'deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bullseye contrib' | sudo tee /etc/apt/sources.list.d/virtualbox.list"
  config.vm.provision :shell, inline: "sudo apt-get update"
  config.vm.provision :shell, inline: "sudo apt-get install linux-headers-$(uname -r) dkms -y"
  config.vm.provision :shell, inline: "sudo apt-get install virtualbox-6.1 -y"
  config.vm.provision :shell, inline: "sudo apt-get install virtualbox-ext-pack-6.1 -y"
  config.vm.provision :shell, inline: "wget https://download.virtualbox.org/virtualbox/6.1.36/Oracle_VM_VirtualBox_Extension_Pack-6.1.36.vbox-extpack"
  config.vm.provision :shell, inline: "sudo vboxmanage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.36.vbox-extpack"
  config.vm.provision :shell, inline: "usermod -aG vboxusers vagrant"


  # Install vagrant
  config.vm.provision :shell, inline: "sudo apt-get install gpg"
  config.vm.provision :shell, inline: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"
  config.vm.provision :shell, inline: "echo 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main' | sudo tee /etc/apt/sources.list.d/hashicorp.list"
  config.vm.provision :shell, inline: "sudo apt-get update && sudo apt-get install vagrant"
  config.vm.provision :shell, inline: "sudo apt-get update && sudo apt-get install rsync -y"

  # Download git
  config.vm.provision :shell, inline: "sudo git clone https://github.com/Sithi5/Inception-of-Things.git"


  # Restart
  config.vm.provision :shell, inline: "sudo shutdown now"

end
