USER_NAME = "Sithis"
USER_PASSWORD = "IOT"


Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "debian 11 bullseye64"

  # Shared folder
  config.vm.synced_folder "../", "/home/vagrant/synced_folder"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = "mabouce_debian_11_bullseye64"
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 4
  end

  # Update repositories
  config.vm.provision :shell, inline: "sudo apt-get update -y"

  # Upgrade installed packages
  config.vm.provision :shell, inline: "sudo apt-get upgrade -y"

  # Vim
  config.vm.provision :shell, inline: "sudo apt-get install vim -y"

  # Git
  config.vm.provision :shell, inline: "sudo apt-get install git -y"

  # Install vagrant and libvirt
  config.vm.provision :shell, inline: "sudo apt-get install vagrant-libvirt libvirt-daemon-system -y"
  config.vm.provision :shell, inline: "sudo usermod --append --groups libvirt vagrant"

  # Download git
  config.vm.provision :shell, inline: "sudo git clone https://github.com/Sithi5/Inception-of-Things.git"

  # Install kubectl
  config.vm.provision :shell, inline: "sudo apt-get install -y apt-transport-https"
  config.vm.provision :shell, inline: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
  config.vm.provision :shell, inline: "echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' | sudo tee -a /etc/apt/sources.list.d/kubernetes.list"
  config.vm.provision :shell, inline: "sudo apt-get update -y"
  config.vm.provision :shell, inline: "sudo apt-get install -y kubectl"

  # Restart
  config.vm.provision :shell, inline: "sudo shutdown -r now"

end
