# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "centos/stream8"
BOX_AUTO_UPDATE = false
VM_USER = 'iot'
USER = 'iot'
VM_NAME_MASTER = 'jcammasS'
# HOST_PATH = '/home/' + USER + '/'
HOST_PATH = 'C:\Work\deployment\Inception-of-Things\p2'
# GUEST_PATH_MASTER = '/home/' + VM_USER + '/' + VM_NAME_MASTER
GUEST_PATH_MASTER = HOST_PATH + '/' + VM_NAME_MASTER
MEM = 4096
CPUS = 4
MASTER_IP = "192.168.42.110"
# MASTER_IP = "192.168.56.0/21"

disable_firewall = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL


Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_url = "https://app.vagrantup.com/centos/boxes/stream8/versions/20210210.0/providers/virtualbox.box"
  config.vm.box_check_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.ssh.insert_key = false
	config.vm.provision "shell", inline: disable_firewall
  config.vm.provider "virtualbox" do |v|
    v.memory = MEM
    v.cpus = CPUS
  end
  config.vm.define VM_NAME_MASTER do |master|
    master.vm.hostname = VM_NAME_MASTER
    master.vm.synced_folder HOST_PATH, GUEST_PATH_MASTER, type: "virtualbox"
    master.vm.network "private_network", ip: MASTER_IP, hostname: false, virtualbox__intnet: "08net"
    master.vm.provision "shell", privileged: true, path: "scripts/setup.sh", args: [MASTER_IP]
    master.vm.provider "virtualbox" do |v|
            v.name = VM_NAME_MASTER
    end
  end
  config.vm.network "forwarded_port", guest: 81, host: 81, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
end