# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "centos/7"
# BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
BOX_AUTO_UPDATE = false
VM_USER = 'iot'
USER = 'iot'
VM_NAME_MASTER = 'jcammasS'
# HOST_PATH = '/home/' + USER + '/'
HOST_PATH = '/Users/julien/42/IoT/p2'
# GUEST_PATH_MASTER = '/home/' + VM_USER + '/' + VM_NAME_MASTER
GUEST_PATH_MASTER = '/Users/julien/42/IoT/p2' + '/' + VM_NAME_MASTER 
MEM = 4096
CPUS = 4
MASTER_IP = "192.168.42.110"
# MASTER_IP = "192.168.56.0/21"

disable_firewall = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL


Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.ssh.insert_key = false 
  # config.vbguest.installer_options = { allow_kernel_upgrade: true }
	config.vm.provision "shell", inline: disable_firewall
  config.vm.provider "virtualbox" do |v|
    v.memory = MEM
    v.cpus = CPUS
  end
  config.vm.define VM_NAME_MASTER do |master|
    master.vm.hostname = VM_NAME_MASTER
    master.vm.synced_folder HOST_PATH, GUEST_PATH_MASTER 
    master.vm.network "private_network", ip: MASTER_IP, hostname: true, virtualbox__intnet: "08net"
    master.vm.provision "shell", privileged: true, path: "scripts/setup.sh", args: [MASTER_IP]
  end
  config.vm.network "forwarded_port", guest: 80, host: 80, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
end