VAGRANT_BOX = 'centos/7'

VM_NAME_MASTER = 'mabouceS'
VM_NAME_WORKER = 'maginistSW'

HOST_PATH = '/home/vagrant/synced_folder/p1'

GUEST_PATH_MASTER = HOST_PATH + '/' + VM_NAME_MASTER
GUEST_PATH_WORKER = HOST_PATH + '/' + VM_NAME_WORKER
MEM = 2048
CPUS = 2
MASTER_IP = "192.168.42.110"
WORKER_IP = "192.168.42.111"

Vagrant.configure(2) do |config|
  config.vm.box = VAGRANT_BOX
  config.ssh.insert_key = true
  config.vm.provision "shell", inline: <<-SHELL
  yum update
  yum upgrade
  SHELL
  config.vm.provider "virtualbox" do |v|
    v.memory = MEM
    v.cpus = CPUS
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.gui = false

  end

  config.vm.define VM_NAME_MASTER do |master|
    master.vm.hostname = VM_NAME_MASTER
    master.vm.synced_folder HOST_PATH, GUEST_PATH_MASTER
    master.vm.network "private_network", ip: MASTER_IP
    master.vm.provider "virtualbox" do |v|
      v.name = VM_NAME_MASTER
    end
  end

  config.vm.define VM_NAME_WORKER do |worker|
    worker.vm.hostname = VM_NAME_WORKER
    worker.vm.synced_folder HOST_PATH, GUEST_PATH_WORKER
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |v|
      v.name = VM_NAME_WORKER
    end
  end

end
