# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS

VAGRANT_BOX = 'centos/8'
VM_NAME_MASTER = 'jcammasS'
VM_NAME_WORKER = 'jcammasSW'
VM_USER = 'iot'
USER = 'iot'
# HOST_PATH = '/home/' + USER + '/'
HOST_PATH = '/Users/julien/42/IoT/p2'
# GUEST_PATH_WORKER = '/home/' + VM_USER + '/' + VM_NAME_WORKER
# GUEST_PATH_MASTER = '/home/' + VM_USER + '/' + VM_NAME_MASTER
GUEST_PATH_MASTER = '/Users/julien/42/IoT/p2' + '/' + VM_NAME_MASTER 
GUEST_PATH_WORKER = '/Users/julien/42/IoT/p2' + '/' + VM_NAME_WORKER 
MEM = 512
CPUS = 1
# MASTER_IP = "192.168.42.110"
MASTER_IP = "192.168.56.0/21"
# WORKER_IP = "192.168.42.111"
WORKER_IP = "192.168.56.0/22"

Vagrant.configure(2) do |config|
  config.vm.box = VAGRANT_BOX
  config.ssh.insert_key = true
  config.vm.provision "shell", inline: <<-SHELL 
  yum update
  yum upgrade
  SHELL
  config.vm.provider "virtualbox" do |v|
    v.memory = MEM
    v.cpus = CPUS
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.gui = true

  end

  config.vm.define VM_NAME_MASTER do |master|
    master.vm.hostname = VM_NAME_MASTER
    master.vm.synced_folder HOST_PATH, GUEST_PATH_MASTER 
    master.vm.network "private_network", ip: MASTER_IP
    config.vm.synced_folder '.', '/home/' + VM_USER + '', disabled: true

    master.vm.provider "virtualbox" do |v|
      v.name = VM_NAME_MASTER
    end
  end

  config.vm.define VM_NAME_WORKER do |worker|
    worker.vm.hostname = VM_NAME_WORKER
    worker.vm.synced_folder HOST_PATH, GUEST_PATH_WORKER
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |v|
      v.name = VM_NAME_WORKER
    end
  end

end