# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOX = "centos/stream8"

VM_NAME_SERVER = 'jcammasS'
VM_NAME_AGENT = 'jcammasSW'

MEM = 1024
CPUS = 1
SERVER_IP = "192.168.42.110"
AGENT_IP = "192.168.42.111"

Vagrant.configure("2") do |config|
  # configuration globale de nos VM
  config.vm.box = VAGRANT_BOX 
  # pour les pcs de 42, utiliser nfs a la place de virtualbox pour les synced_folder
  config.vbguest.installer_options = { allow_kernel_upgrade: true } # lié à notre OS et au vb_guest => important
  config.vm.provider "virtualbox" do |v|
    v.cpus = CPUS
    v.memory = MEM
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  config.vm.provision "shell", inline: "yum install -y net-tools" # install ifconfig

  # configuration de notre server => script server
  config.vm.define VM_NAME_SERVER do |master|
    master.vm.hostname = VM_NAME_SERVER
    master.vm.synced_folder "./", "/vagrant/synced_folder", type: "virtualbox", SharedFoldersEnableSymlinksCreate: true
    master.vm.network "private_network", ip: SERVER_IP, hostname: true, virtualbox__intnet: "08net"
    master.vm.provider "virtualbox" do |v|
      v.name = VM_NAME_SERVER
    end
    master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    master.vm.provision "shell", privileged: true, path: "./scripts/install_master_k3s.sh"
  end

  # configuration de notre worker => script agent
  config.vm.define VM_NAME_AGENT do |worker|
    worker.vm.hostname = VM_NAME_AGENT
    worker.vm.synced_folder "./", "/vagrant/synced_folder", type: "virtualbox", SharedFoldersEnableSymlinksCreate: true
    worker.vm.network "private_network", ip: AGENT_IP, hostname: true, virtualbox__intnet: "08net"
    worker.vm.provider "virtualbox" do |v|
      v.name = VM_NAME_AGENT
    end
    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
    worker.vm.provision "shell", privileged: true, path: "./scripts/install_worker_k3s.sh" 
  end
end