VAGRANT_BOX = "debian/bullseye64"
VM_SYNC_FOLDER = "/home/vagrant/synced_folder"
VM_MEMORY = "4096"
VM_CPUS = 4

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.define "debian 11 bullseye64"

  # Shared folder
  config.vm.synced_folder "../", "/home/vagrant/synced_folder"

  config.vm.provider "virtualbox" do |v|
    # Display the VirtualBox GUI when booting the machine
    v.name = "mabouce_debian_11_bullseye64"
    v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    v.gui = false

    # Customize the amount of memory on the VM:
    v.memory = VM_MEMORY
    v.cpus = VM_CPUS
  end

  # Update repositories

  config.vm.provision :shell, inline: <<-SHELL
  sudo apt-get update -y
  sudo apt-get upgrade -y
  SHELL

  # Vim
  config.vm.provision :shell, inline: "sudo apt-get install vim -y"

  # gnupg
  config.vm.provision :shell, inline: "sudo apt-get -y install gnupg"

  # Install vagrant
  config.vm.provision :shell, inline: <<-SHELL
  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  sudo apt-get update && sudo apt-get install vagrant -y
  SHELL

  # Install virtualbox
  config.vm.provision :shell, inline: <<-SHELL
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  echo "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bullseye contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
  sudo apt-get update
  sudo apt-get install virtualbox-6.1 -y
  SHELL


  # Install kubectl
  config.vm.provision :shell, inline: <<-SHELL
  sudo apt-get install apt-transport-https -y
  sudo apt-get install rsync -y
  sudo apt-get install curl -y
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  sudo apt-get update -y
  sudo apt-get install -y kubectl
  SHELL

  # Restart
  config.vm.provision :shell, inline: "sudo shutdown -r now"

end
