VAGRANT_BOX = "ubuntu/focal64"
VM_SYNC_FOLDER = "/home/vagrant/synced_folder"
VM_MEMORY = "4096"
VM_CPUS = 4

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.define "ubuntu 20.04 focal64"

  # Shared folder
  config.vm.synced_folder "../", "/home/vagrant/synced_folder"

  config.vm.provider "virtualbox" do |v|
    # Display the VirtualBox GUI when booting the machine
    v.name = "mabouce_focal_20.04_focal64"
    v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    v.gui = false

    # Customize the amount of memory on the VM:
    v.memory = VM_MEMORY
    v.cpus = VM_CPUS
  end

  # Update repositories

  config.vm.provision :shell, inline: <<-SHELL
  sudo apt-get update -y
  sudo apt-get upgrade -y
  SHELL

  # Vim
  config.vm.provision :shell, inline: "sudo apt-get install vim -y"

  # Install vagrant
  config.vm.provision :shell, inline: <<-SHELL
  curl -O https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  sudo apt-get install ./vagrant_2.2.9_x86_64.deb -y
  SHELL

  # Install virtualbox
  config.vm.provision :shell, inline: <<-SHELL
  sudo mkdir /etc/vbox/
  echo "* 0.0.0.0/0 ::/0" > networks.conf
  sudo mv networks.conf /etc/vbox/.
  sudo apt-get install virtualbox -y
  SHELL


  # Install kubectl
  config.vm.provision :shell, inline: <<-SHELL
  sudo apt-get install apt-transport-https -y
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  sudo apt-get update -y
  sudo apt-get install -y kubectl
  SHELL

  # Restart
  config.vm.provision :shell, inline: "sudo shutdown -r now"

end
